#
#    ,--.  ,--.         ,--. ,--.  ,--.  ,--.,--.,--.  ,--.  ,--.
#    |  '--'  |,--. ,--.|  | |  |,-'  '-.`--'|  |`--',-'  '-.`--' ,---.  ,---.
#    |  .--.  | \  '  / |  | |  |'-.  .-',--.|  |,--.'-.  .-',--.| .-. :(  .-'
#    |  |  |  |  \   '  '  '-'  '  |  |  |  ||  ||  |  |  |  |  |\   --..-'  `)
#    `--'  `--'.-'  /    `-----'   `--'  `--'`--'`--'  `--'  `--' `----'`----'
#              `---'
#

general:
  language: de_DE